// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZWep3dPLMQYr0hezpE8E8OYvArk9M2_E',
    appId: '1:555742466692:web:bb973c353e5848112068d1',
    messagingSenderId: '555742466692',
    projectId: 'project24-fdae5',
    authDomain: 'project24-fdae5.firebaseapp.com',
    storageBucket: 'project24-fdae5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArdHjv69MvLAecEwLmsP6OO4XDft1jluA',
    appId: '1:555742466692:android:ab8131594df5b0f52068d1',
    messagingSenderId: '555742466692',
    projectId: 'project24-fdae5',
    storageBucket: 'project24-fdae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDobNwKCCBlaXEzepCktOPGWmc2CQIB2xU',
    appId: '1:555742466692:ios:48190a1a1701a0492068d1',
    messagingSenderId: '555742466692',
    projectId: 'project24-fdae5',
    storageBucket: 'project24-fdae5.appspot.com',
    iosBundleId: 'com.example.project24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDobNwKCCBlaXEzepCktOPGWmc2CQIB2xU',
    appId: '1:555742466692:ios:48190a1a1701a0492068d1',
    messagingSenderId: '555742466692',
    projectId: 'project24-fdae5',
    storageBucket: 'project24-fdae5.appspot.com',
    iosBundleId: 'com.example.project24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZWep3dPLMQYr0hezpE8E8OYvArk9M2_E',
    appId: '1:555742466692:web:f1f5741e2080036b2068d1',
    messagingSenderId: '555742466692',
    projectId: 'project24-fdae5',
    authDomain: 'project24-fdae5.firebaseapp.com',
    storageBucket: 'project24-fdae5.appspot.com',
  );

}